### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by OrelRHD** [IvanGrigorov/php-getters-and-setters#1]
Hi !

There is a problem on Linux : You always only have the first property used to make getters/setters/constructor...

The properties are separated by line breaks, and the current code assumes line breaks are represented by \r\n. However, on Linux, line breaks are usually represented by \n only.

I think (but not tested) that change the properties's definition with this can make the job :
let properties = selection.split(/\r?\n/);

**Comment by IvanGrigorov** [comment]
H @OrelRHD i, thanks for the feedback. 
Currently I was using direct string separation without regex and only for CRLF.

I changed it to use regex for all types of EOL separators.
https://github.com/IvanGrigorov/php-getters-and-setters/commit/bdc768879eef80238c57fe788c32ffa44bb1727b

New version is bumped 0.1.3

**Comment by OrelRHD** [comment]
Great, thank you!
